### ISSUE TITLE
Set 11.5 login settings for Docker contexts

### ISSUE THREAD

**Issue by kitzberger** [cron-eu/t3x-cron-context#5]
https://github.com/TYPO3/typo3/blob/11.5/typo3/sysext/core/Configuration/DefaultConfiguration.php#L1232-L1234

```
   'BE' => [
        ...
        'loginRateLimit' => 5,
        'loginRateLimitInterval' => '15 minutes',
        'loginRateLimitIpExcludeList' => '',
     ],
```

Same for `FE` I guess.

**Comment by baschny** [comment]
why do we need this if this is the "Default Configuration" from the core?

**Comment by kitzberger** [comment]
Sorry, I meant to say something like '240 minutes' or '0 minutes' if possible

**Comment by kitzberger** [comment]
I suggest this since it's disabling that check entirely:

```PHP
$GLOBALS['TYPO3_CONF_VARS']['BE']['loginRateLimit']     = '0';
```
